version: "3.9"
services:
  influxdb:
    image: "influxdb:${INFLUXDB_IMAGE_TAG}"
    container_name: grafana-influxdb
    expose:
      - 8086
    volumes:
      - influxdb:/var/lib/influxdb
    restart: always
    environment:
      - "INFLUXDB_GRAPHITE_ENABLED=${INFLUXDB_GRAPHITE_ENABLED}"
      - "INFLUXDB_REPORTING_DISABLED=${INFLUXDB_REPORTING_DISABLED}"
      - "INFLUXDB_DB=internet_speed"
      - "INFLUXDB_USER=${INFLUXDB_USER}"
      - "INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}"
  speedtest-grafana:
    build: .
    image: speedtest-grafana:0.0.2
    container_name: grafana-speedtest
    depends_on:
      - influxdb
    environment:
      - "SPEEDTEST_INTERVAL=${SPEEDTEST_INTERVAL}"
      - "SPEEDTEST_SERVER_ID=${SPEEDTEST_SERVER_ID}"
      - "INFLUXDB_HOST=influxdb"
      - "INFLUXDB_PORT=8086"
      - "INFLUXDB_DB=internet_speed"
      - "INFLUXDB_USER=${INFLUXDB_USER}"
      - "INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dashboard
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-config/:/etc/grafana/provisioning
    depends_on:
      - influxdb
      - speedtest-grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}"

volumes:
  influxdb:
  grafana-storage:
